IF
NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'TESTDB')
BEGIN
    CREATE
DATABASE TESTDB;
END;
GO

USE TESTDB;
GO

CREATE TABLE USR_CUST
(
    CUST_UUID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FULL_NM   VARCHAR(100)        NOT NULL,
    EMAIL     VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NBR VARCHAR(20),
    DT_CRT    DATETIME2                    DEFAULT GETDATE(),
    DT_UPD    DATETIME2                    DEFAULT GETDATE()
);
GO

CREATE TABLE USR_CUST_ACCT
(
    ACCT_UUID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CUST_UUID UNIQUEIDENTIFIER NOT NULL,
    ACCT_NBR  VARCHAR(50)      NOT NULL,
    ACCT_TYPE VARCHAR(10)      NOT NULL,
    ACCT_NAME VARCHAR(100),
    DT_CRT    DATETIME2                    DEFAULT GETDATE(),
    DT_UPD    DATETIME2                    DEFAULT GETDATE(),

    CONSTRAINT FK_ACCT_CUST FOREIGN KEY (CUST_UUID) REFERENCES USR_CUST (CUST_UUID),
    CONSTRAINT UQ_CUST_ACCT UNIQUE (CUST_UUID, ACCT_NBR),
    CONSTRAINT CHK_ACCT_TYPE CHECK (ACCT_TYPE IN ('S', 'D', 'CC'))
);
GO

CREATE TABLE USR_STAFF
(
    STAFF_UUID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    USR_NM     VARCHAR(50) UNIQUE  NOT NULL,
    PWD_HSH    VARCHAR(255)        NOT NULL,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    FULL_NAME  VARCHAR(100)        NOT NULL,
    ROLE       VARCHAR(20)         NOT NULL,
    IS_ACTIVE  BIT                          DEFAULT 1,
    LAST_LOGIN DATETIME2 NULL,
    DT_CRT     DATETIME2                    DEFAULT GETDATE(),
    DT_UPD     DATETIME2                    DEFAULT GETDATE(),

    CONSTRAINT CHK_ROLE CHECK (ROLE IN ('ADMIN', 'OPS', 'VIEWER'))
);
GO

CREATE TABLE TRX_DUITLATER
(
    TRX_UUID     UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CUST_UUID    UNIQUEIDENTIFIER NOT NULL,
    ACCT_UUID    UNIQUEIDENTIFIER NOT NULL,
    IDEMP_KEY    UNIQUEIDENTIFIER NOT NULL,

    ORIG_AMT     DECIMAL(15, 2)   NOT NULL,
    ORIG_CCY     VARCHAR(3)       NOT NULL,

    CONV_AMT     DECIMAL(15, 2)   NOT NULL,
    CONV_CCY     VARCHAR(3)       NOT NULL,

    EXCH_RATE    DECIMAL(19, 6)   NOT NULL,

    DT_SCHED     DATE             NOT NULL,
    TO_ACCT_NBR  VARCHAR(50)      NOT NULL,
    TO_CUST_NAME VARCHAR(100),

    STS_CD       VARCHAR(20)                  DEFAULT 'SCHEDULED',
    STS_RSN      VARCHAR(200),
    STS_UPD_DT   DATETIME2                    DEFAULT GETDATE(),

    ERR_MSG      VARCHAR(500),

    DT_CRT       DATETIME2                    DEFAULT GETDATE(),
    DT_UPD       DATETIME2                    DEFAULT GETDATE(),

    CONSTRAINT FK_TRX_CUST FOREIGN KEY (CUST_UUID) REFERENCES USR_CUST (CUST_UUID),
    CONSTRAINT FK_TRX_ACCT FOREIGN KEY (ACCT_UUID) REFERENCES USR_CUST_ACCT (ACCT_UUID),
    CONSTRAINT UQ_IDEMP_KEY UNIQUE (IDEMP_KEY),
    CONSTRAINT CHK_STATUS CHECK (STS_CD IN ('SCHEDULED', 'CANCELLED', 'COMPLETED'))
);
GO

CREATE INDEX IDX_TRX_STATUS_SCHED ON TRX_DUITLATER (STS_CD, DT_SCHED DESC);
CREATE INDEX IDX_TRX_CUST_STATUS ON TRX_DUITLATER (CUST_UUID, STS_CD, DT_SCHED DESC);
CREATE INDEX IDX_TRX_ACCT ON TRX_DUITLATER (ACCT_UUID);
CREATE UNIQUE INDEX IDX_TRX_UUID ON TRX_DUITLATER (TRX_UUID);
CREATE UNIQUE INDEX IDX_IDEMP_KEY ON TRX_DUITLATER (IDEMP_KEY);
GO

INSERT INTO USR_CUST (CUST_UUID, FULL_NM, EMAIL, PHONE_NBR) VALUES
('715db132-012c-47b8-86c8-a169853eaae3', 'John Doe', 'john@duitlater.com', '0123456789'),
('31f3ae79-2254-4d97-986a-691abc4f7292', 'Jane Smith', 'jane@duitlater.com', '0198765432');
GO

INSERT INTO USR_CUST_ACCT (CUST_UUID, ACCT_UUID, ACCT_NBR, ACCT_TYPE, ACCT_NAME) VALUES
('715db132-012c-47b8-86c8-a169853eaae3', 'c6ba0062-e9fb-4da0-a125-b618b7705ad1', 'SAVINGS_001', 'S', 'John''s Savings'),
('715db132-012c-47b8-86c8-a169853eaae3', '25ea415c-29aa-4174-8f43-2462313599dd', 'CURRENT_001', 'D', 'John''s Current'),
('31f3ae79-2254-4d97-986a-691abc4f7292', '0de7cab1-e12c-40ed-9a63-87b3ec10c41f', 'SAVINGS_002', 'S', 'Jane''s Savings');
GO

INSERT INTO USR_STAFF (USR_NM, PWD_HSH, EMAIL, FULL_NAME, ROLE) VALUES
('admin', '$2a$10$WacQt50h4aIDcJjJ.iFdXuH1f.Ab4LB3Fm6sOkOJ7jUm74cLjI9Iy', 'admin@duitlater.com', 'System Administrator', 'ADMIN')
GO